- name: prepare multienvironment
  hosts: localhost
  connection: local
  vars:
    multienv_union:
      - base
      - dev
      # - stage
      # - production
  roles:
    - role: jobcespedes.multienv
